# Generated by Django 3.0.4 on 2020-03-14 08:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberType', models.CharField(choices=[('BTECH', 'Bachelor'), ('MTECH', 'Master'), ('_PhD_', 'Doctorate'), ('FCLT_', 'Faculty')], default='BTECH', max_length=5)),
                ('address', models.TextField()),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2021, 3, 14, 14, 2, 3, 257826))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
