# Generated by Django 3.0.4 on 2020-03-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.IntegerField(max_length=13)),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('availability', models.IntegerField()),
                ('authors', models.ManyToManyField(to='LibraryMS.Author')),
            ],
        ),
    ]
