# Generated by Django 3.0.4 on 2020-03-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryMS', '0002_auto_20200314_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.BigIntegerField(max_length=13),
        ),
    ]
